### ISSUE TITLE
ArXiv Link

### ISSUE THREAD

**Issue by c-liangyu** [allenai/procthor-10k#2]
Hi! May I know if there is an ArXiv link to this repo? 👀
Thank you!

**Comment by mattdeitke** [comment]
Yep, came out recently!

Check out the website: https://procthor.allenai.org/
and the arXiv: https://arxiv.org/abs/2206.06994

We're rolling out how an update to use this repo to access the 10k houses so that they can use semantic versioning and some other things :)

**Comment by c-liangyu** [comment]
Cool! Will keep heads up for your update.
